export const SAMPLE_LISTINGS = Object.freeze([
  {
    id: "modern-downtown-loft",
    title: "Modern Downtown Loft",
    address: "123 Main St, Chicago, IL - Fulton Market District",
    price: 2800,
    beds: 2,
    baths: 2,
    sqft: 1200,
    imageUrl: "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80",
    propertyType: "Luxury",
    type: "2bed",
    pets: ["dogs", "cats"] as const,
    amenities: ["parking", "gym", "laundry"] as const,
    features: ["transit", "nightlife"] as const,
    details: {
      description: "Luxurious downtown loft featuring modern amenities, floor-to-ceiling windows, and stunning city views. Recently renovated with high-end finishes throughout.",
      images: [
        "https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "In-Unit Laundry", included: true },
        { name: "Central AC", included: true },
        { name: "Dishwasher", included: true },
        { name: "Fitness Center", included: true },
        { name: "Package Room", included: true },
        { name: "Roof Deck", included: true },
        { name: "Dog Run", included: false },
        { name: "Pool", included: false },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Dogs and cats welcome. Breed restrictions apply. Maximum 2 pets per unit.",
        deposit: 500,
        rent: 50,
      },
      availability: "2024-05-01",
      leaseTerms: ["12 months", "18 months", "24 months"],
      screeningFee: {
        amount: 50,
        paidBy: "tenant",
      },
      location: {
        lat: 41.8781,
        lng: -87.6298,
        neighborhood: "The Loop",
        walkScore: 98,
        transitScore: 100,
        nearbyPlaces: [
          { name: "Millennium Park", distance: "0.3 miles" },
          { name: "Chicago Riverwalk", distance: "0.2 miles" },
          { name: "State Street Shopping", distance: "0.4 miles" },
          { name: "Grant Park", distance: "0.5 miles" },
        ],
      },
    }
  },
  {
    id: "luxury-high-rise-studio",
    title: "Luxury High-Rise Studio",
    address: "456 Park Ave, New York, NY - Meatpacking District",
    price: 3500,
    beds: 1,
    baths: 1,
    sqft: 750,
    imageUrl: "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
    propertyType: "Luxury",
    type: "studio",
    pets: ["cats"] as const,
    amenities: ["gym", "doorman", "elevator"] as const,
    features: ["nightlife", "shopping"] as const,
    details: {
      description: "Stunning high-rise studio apartment with panoramic city views, modern finishes, and premium building amenities. Perfect for urban professionals.",
      images: [
        "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "24/7 Doorman", included: true },
        { name: "Fitness Center", included: true },
        { name: "Elevator", included: true },
        { name: "Package Room", included: true },
        { name: "Roof Deck", included: true },
        { name: "Bike Storage", included: true },
        { name: "Pool", included: false },
        { name: "Parking", included: false },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Cats only. Maximum 2 pets per unit.",
        deposit: 350,
        rent: 35,
      },
      availability: "2024-06-01",
      leaseTerms: ["12 months", "18 months"],
      screeningFee: {
        amount: 50,
        paidBy: "tenant",
      },
      location: {
        lat: 40.7411,
        lng: -74.0055,
        neighborhood: "Meatpacking District",
        walkScore: 95,
        transitScore: 100,
        nearbyPlaces: [
          { name: "High Line", distance: "0.1 miles" },
          { name: "Chelsea Market", distance: "0.3 miles" },
          { name: "Whitney Museum", distance: "0.2 miles" },
          { name: "Hudson River Park", distance: "0.4 miles" },
        ],
      },
    }
  },
  {
    id: "spacious-river-north",
    title: "Spacious River North Apartment",
    address: "789 River St, Chicago, IL",
    price: 2500,
    beds: 2,
    baths: 2,
    sqft: 1100,
    imageUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80",
    propertyType: "Comfortable",
    type: "2bed",
    pets: ["dogs"] as const,
    amenities: ["parking", "laundry"] as const,
    features: ["quiet", "parks"] as const,
    details: {
      description: "Beautifully renovated apartment in the heart of River North featuring hardwood floors, stainless steel appliances, and an open concept layout.",
      images: [
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "In-Unit Laundry", included: true },
        { name: "Parking Space", included: true },
        { name: "Central AC", included: true },
        { name: "Dishwasher", included: true },
        { name: "Storage Unit", included: true },
        { name: "Balcony", included: true },
        { name: "Gym", included: false },
        { name: "Pool", included: false },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Dogs welcome. Breed restrictions apply. Maximum weight 50 lbs.",
        deposit: 400,
        rent: 45,
      },
      availability: "2024-07-01",
      leaseTerms: ["12 months", "24 months"],
      screeningFee: {
        amount: 45,
        paidBy: "tenant",
      },
      location: {
        lat: 41.8925,
        lng: -87.6354,
        neighborhood: "River North",
        walkScore: 95,
        transitScore: 95,
        nearbyPlaces: [
          { name: "Merchandise Mart", distance: "0.3 miles" },
          { name: "Chicago Riverwalk", distance: "0.2 miles" },
          { name: "Michigan Avenue", distance: "0.5 miles" },
          { name: "Navy Pier", distance: "1.0 miles" },
        ],
      },
    }
  },
  {
    id: "cozy-lincoln-park",
    title: "Cozy Lincoln Park Studio",
    address: "321 Lincoln Ave, Chicago, IL",
    price: 1800,
    beds: 1,
    baths: 1,
    sqft: 600,
    imageUrl: "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
    propertyType: "Comfortable",
    type: "studio",
    pets: ["cats"] as const,
    amenities: ["laundry"] as const,
    features: ["quiet", "parks"] as const,
    details: {
      description: "Charming studio apartment in the heart of Lincoln Park. Features modern appliances, hardwood floors, and abundant natural light. Steps from Lincoln Park Zoo and lakefront trails.",
      images: [
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "In-Unit Laundry", included: true },
        { name: "Central AC", included: true },
        { name: "Dishwasher", included: true },
        { name: "Hardwood Floors", included: true },
        { name: "Storage Unit", included: true },
        { name: "Bike Room", included: true },
        { name: "Fitness Center", included: false },
        { name: "Parking", included: false },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Cats only. Maximum 2 cats per unit.",
        deposit: 300,
        rent: 30,
      },
      availability: "2024-05-15",
      leaseTerms: ["12 months", "18 months"],
      screeningFee: {
        amount: 45,
        paidBy: "tenant",
      },
      location: {
        lat: 41.9256,
        lng: -87.6474,
        neighborhood: "Lincoln Park",
        walkScore: 94,
        transitScore: 85,
        nearbyPlaces: [
          { name: "Lincoln Park Zoo", distance: "0.3 miles" },
          { name: "Lakefront Trail", distance: "0.5 miles" },
          { name: "DePaul University", distance: "0.6 miles" },
          { name: "Whole Foods Market", distance: "0.2 miles" },
        ],
      },
    }
  },
  {
    id: "west-loop-penthouse",
    title: "West Loop Penthouse",
    address: "567 Madison St, Chicago, IL",
    price: 4500,
    beds: 3,
    baths: 2.5,
    sqft: 2200,
    imageUrl: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
    propertyType: "Luxury",
    type: "3bed",
    pets: ["dogs", "cats"] as const,
    amenities: ["parking", "gym", "pool", "doorman"] as const,
    features: ["nightlife", "shopping"] as const,
    details: {
      description: "Spectacular penthouse with panoramic city views, featuring premium finishes, a gourmet kitchen, and expansive private terrace. Full-service luxury building in prime West Loop location.",
      images: [
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "24/7 Doorman", included: true },
        { name: "Heated Pool", included: true },
        { name: "Fitness Center", included: true },
        { name: "Private Parking", included: true },
        { name: "Private Terrace", included: true },
        { name: "Wine Cellar", included: true },
        { name: "Pet Spa", included: true },
        { name: "Concierge", included: true },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Dogs and cats welcome. No breed or size restrictions.",
        deposit: 750,
        rent: 75,
      },
      availability: "2024-06-01",
      leaseTerms: ["12 months", "24 months"],
      screeningFee: {
        amount: 75,
        paidBy: "tenant",
      },
      location: {
        lat: 41.8825,
        lng: -87.6447,
        neighborhood: "West Loop",
        walkScore: 98,
        transitScore: 95,
        nearbyPlaces: [
          { name: "Restaurant Row", distance: "0.1 miles" },
          { name: "Whole Foods", distance: "0.2 miles" },
          { name: "Morgan Station", distance: "0.3 miles" },
          { name: "Mary Bartelme Park", distance: "0.4 miles" },
        ],
      },
    }
  },
  {
    id: "fulton-market-loft",
    title: "Fulton Market Loft",
    address: "890 Fulton St, Chicago, IL",
    price: 3200,
    beds: 2,
    baths: 2,
    sqft: 1400,
    imageUrl: "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?auto=format&fit=crop&q=80",
    propertyType: "Luxury",
    type: "2bed",
    pets: ["dogs"] as const,
    amenities: ["parking", "gym", "elevator"] as const,
    features: ["transit", "restaurants"] as const,
    details: {
      description: "Industrial-chic loft in the heart of Fulton Market featuring exposed brick, timber beams, and floor-to-ceiling windows. Modern amenities meet historic character in this vibrant neighborhood.",
      images: [
        "https://images.unsplash.com/photo-1505873242700-f289a29e1e0f?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1493809842364-78817add7ffb?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1512918728675-ed5a9ecdebfd?auto=format&fit=crop&q=80",
        "https://images.unsplash.com/photo-1536376072261-38c75010e6c9?auto=format&fit=crop&q=80",
      ],
      amenities: [
        { name: "Elevator", included: true },
        { name: "Fitness Center", included: true },
        { name: "Reserved Parking", included: true },
        { name: "Package Room", included: true },
        { name: "Bike Storage", included: true },
        { name: "Rooftop Deck", included: true },
        { name: "Dog Run", included: false },
        { name: "Pool", included: false },
      ],
      petPolicy: {
        allowed: true,
        restrictions: "Dogs welcome. Breed restrictions apply. Maximum 1 dog per unit.",
        deposit: 500,
        rent: 50,
      },
      availability: "2024-07-15",
      leaseTerms: ["12 months", "18 months"],
      screeningFee: {
        amount: 50,
        paidBy: "tenant",
      },
      location: {
        lat: 41.8864,
        lng: -87.6487,
        neighborhood: "Fulton Market",
        walkScore: 96,
        transitScore: 92,
        nearbyPlaces: [
          { name: "Google Office", distance: "0.2 miles" },
          { name: "Time Out Market", distance: "0.3 miles" },
          { name: "Morgan Station", distance: "0.4 miles" },
          { name: "Randolph Restaurant Row", distance: "0.1 miles" },
        ],
      },
    }
  },
])

export type SampleListing = typeof SAMPLE_LISTINGS[number]